schema_version = "1.0.0"
id = "wakatime_blender"
name = "Wakatime Blender Integration"
version = "1.0.0"
type = "add-on"
namespace = "wakatime_blender"
author = "Luckmuc, WakaTime"
tagline = "Track your Blender project time automatically with Wakatime."
maintainer = "Luckmuc <your-email@example.com>"
description = "Automatic time tracking for Blender projects using WakaTime."
blender_version_min = "4.5.0"
website = "https://github.com/allista/WakatimeBlender"
tracker_url = "https://github.com/allista/WakatimeBlender/issues"
license = ["MIT"]
category = "System"